module.exports = {
  DEFAULT_SELLER: {
    name: "StudyUpIndia",
    email: "teamstudyupindia1@gmail.com",
    phone: "9868222297",
    address: "Rohini, Sector-11, Delhi, India",
    city: "Delhi",
    state: "Delhi",
    pincode: "110085",
    password: "12345678",
    role: "seller",
    publication: "NCERT",
    source: "internal",
    status: "active",
  },
  DEFAULT_ADMIN: {
    name: "Harsh Kumar",
    email: "harshkumarspj+admin@gmail.com",
    password: "12345678",
    role: "admin",
    source: "internal",
    status: "active",
  },
  DEFAULT_BUYER: {
    name: "Harsh Kumar",
    email: "harshkumarspj@gmail.com",
    phone: "9122532589",
    address: "Rohini, Sector-5, Delhi, India",
    city: "Delhi",
    state: "Delhi",
    pincode: "110085",
    password: "12345678",
    role: "buyer",
    source: "internal",
    status: "active",
  },
};